version: '3.8'

services:
  backend:
    image: node:18
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "6002:3000"
    command: ["sh", "-c", "npm install && npm start"]

  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "6001:4200"
    command: ["sh", "-c", "npm install && npm start"]
    depends_on:
      - backend

  # db:
  #   image: postgres:15
  #   container_name: database
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   ports:
  #     - "6003:5432"

volumes:
  backend:
  frontend: